### ISSUE TITLE
How to build and connect 

### ISSUE THREAD

**Issue by Vasilis553** [4malgama/gtanks_server_remake#1]
Hello I build whi gradlew sShadowJar and the Java jar the server and what client I use to connect and what resource server

And what ip and port the server runs

**Comment by 4malgama** [comment]
Hello.

The server opens on the local IP (127.0.01) and port 5000. You can change it in the main file src/main/java/amalgama/Main.java .

**Comment by BodyaJS** [comment]
каку джаву юзает сервер?

**Comment by Vasilis553** [comment]
Client?

**Comment by Vasilis553** [comment]
And gradlew error

**Comment by 4malgama** [comment]
> каку джаву юзает сервер?

JDK 17

**Comment by 4malgama** [comment]
> Client?

In the repository description, you can see '... latest cleint'. This means that the server is designed for the latest version of the GTanks client version. You can change the settings in the Local AppData/GTanks client folder. The file is called socket.cfg.

**Comment by Vasilis553** [comment]
Maybe a link of the download because the main website is down?

**Comment by Vasilis553** [comment]
Do you have media fire or drop box the jdk 17?

**Comment by BodyaJS** [comment]
C:\Users\Bodya\Desktop\gtanks_server_remake-master>java -jar build\libs\gtanks_server_remake-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/xml/bind/JAXBContext
        at amalgama.xml.MapParser.<init>(MapParser.java:15)
        at amalgama.MapLoader.loadMaps(MapLoader.java:14)
        at amalgama.ConfigLoader.loadStartup(ConfigLoader.java:13)
        at amalgama.Main.main(Main.java:13)
Caused by: java.lang.ClassNotFoundException: jakarta.xml.bind.JAXBContext
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 4 more

C:\Users\Bodya\Desktop\gtanks_server_remake-master>

**Comment by JhonnyBeige** [comment]
so i build the server with "gradlew.bat build" and got build folder with libs\gtanks_server_remake-1.0-SNAPSHOT.jar file and classes folder with .class files. i also have files folder with .json files. how all these files should be orginized? how should the final server folder look like. does it need  gtanks.sql database?

**Comment by JhonnyBeige** [comment]
how do you setup the database ? i created db_gtanks database with subroot user and xxXX6677 password.  what .sql file do u use?
i have the same error as here https://github.com/4malgama/gtanks_server_remake/issues/2

**Comment by 4malgama** [comment]
> how do you setup the database ? i created db_gtanks database with subroot user and xxXX6677 password. what .sql file do u use? i have the same error as here #2

Hi. You can find instructions on how to set up the server from this enthusiast [in his answer](https://github.com/4malgama/gtanks_server_remake/issues/2#issuecomment-2158248147)
